spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret_key: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
